### PR TITLE
update CMakeLists.txt to 3.5 and fix fluidsynth search

### PR DESCRIPTION
**Pull request by AlwinEsch**

### CODE REVIEW

**Comment by AlwinEsch** [comment]
This addon works only on Linux.
According to https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#building-on-os-x on Windows and Mac it would also be possible, but with our Jenkins the glib or pkgconfig (in Windows) is not available

Someone a idea or change allowed OS only to Linux?

**Comment by AlwinEsch** [comment]
@notspiff is there a way known to use this addon on other OS's except Linux? Otherwise, I would limit the support for now only on Linux.

**Comment by AlwinEsch** [comment]
@Rechi is on last commit the remove of OSX, OK for you? I want also to disable AppVeyor for this, OK too?

**Comment by Rechi** [comment]
It's fine for me.
I disabled  AppVeyor, so if you force rebase your PR, it' shouldn't be triggered again.

**Pull request merged**
